version: '{build}'
init:
  - 'git config --global core.autocrlf true'
branches:
  only:
    - master
skip_commits:
  files:
    - LICENSE
environment:
  nodejs_version: 8
platform:
  - x64
install:
  - ps: 'Install-Product node $env:nodejs_version $env:platform'
  - 'node --version && npm --version'
  - 'npm i -g gitbook-cli'
  - 'choco install calibre'
  - 'refreshenv'
  - 'npm i -g svgexport'
build_script:
  - 'if exist _book rd /Q /S _book'
  - 'gitbook install'
  - 'gitbook build'
  - 'gitbook pdf ./ ./juice-shop.pdf'
  - 'gitbook mobi ./ ./juice-shop.mobi'
  - 'gitbook epub ./ ./juice-shop.epub'
  - 'cp ./book-ctf.json ./book.json'
  - 'cp ./cover-ctf.jpg ./cover.jpg'
  - 'cp ./cover-ctf_small.jpg ./cover_small.jpg'
  - 'gitbook pdf ./ ./juice-shop-ctf.pdf'
  - 'gitbook mobi ./ ./juice-shop-ctf.mobi'
  - 'gitbook epub ./ ./juice-shop-ctf.epub'
test: off
artifacts:
  - path: '*.pdf'
  - path: '*.mobi'
  - path: '*.epub'
  - path: '_book'
deploy:
  provider: FTP
  protocol: ftp
  host: ftp.strato.de
  username: kimminich.de
  password:
    secure: Vu/o5fi8cCRsc9VmD4B/Xg==
  folder: pwning-juice-shop
  application: _book.zip
notifications:
  -
    provider: Slack
    incoming_webhook:
      secure: KzO8e88B0LKqAI0BQM6lNhCIn9rxAava3AcdVJDyTw420OLIAlK+qzzbLXaR0jSH9zIJz9zu0iGS1iaqu9Co+6owYUrHJlBGrUZ/lZNCsDo=
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
