image: Visual Studio 2022
version: '{build}'
init:
  - 'git config --global core.autocrlf true'
branches:
  only:
    - antora-migration
skip_commits:
  files:
    - LICENSE
    - README.md
environment:
  nodejs_version: 18
  ruby_version: 32
install:
  - ps: 'Install-Product node $env:nodejs_version'
  - 'mkdir C:\Users\appveyor\AppData\Roaming\npm'
  - 'node --version && npm --version'
  - 'npx antora -v'
  - 'set PATH=C:\Ruby%ruby_version%\bin;%PATH%'
  - 'ruby -v && gem -v'
  - 'gem install asciidoctor-epub3'
  - 'asciidoctor-epub3 -v'
  - 'gem install asciidoctor-pdf'
  - 'asciidoctor-pdf -v'
build_script:
  - 'if exist build rd /Q /S build'
  - 'npm i @antora/lunr-extension'
  - 'npx antora antora-playbook.yml'
  - ps: 'asciidoctor-epub3 -D output docs/modules/ROOT/pages/book.adoc'
  - ps: 'asciidoctor-pdf -D output -a pdf-theme=basic -a pdf-themesdir=resources/themes -a pdf-fontsdir=resources/fonts docs/modules/ROOT/pages/book.adoc'
test: off
artifacts:
  - path: 'build'
  - path: 'output/book.pdf'
  - path: 'output/book.epub'
deploy:
  provider: FTP
  protocol: sftp
  host: ssh.strato.de
  username: kimminich.de
  password:
    secure: Vu/o5fi8cCRsc9VmD4B/Xg==
  folder: pwning-juice-shop/antora
  application: build.zip
  on:
    branch: antora-migration
notifications:
  -
    provider: Webhook
    url:
      secure: c4xwvfA2YpTyASkpasFt2oTuz51teT2qAgq9gU45flir+cdJeT1/utEXowV/TsvmjrsUPRawd/ZNch9ZnAMZCg==
    method: GET
  -
    provider: Slack
    incoming_webhook:
      secure: KzO8e88B0LKqAI0BQM6lNhCIn9rxAava3AcdVJDyTw420OLIAlK+qzzbLXaR0jSH9zIJz9zu0iGS1iaqu9Co+6owYUrHJlBGrUZ/lZNCsDo=
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
