image: Visual Studio 2022
version: '{build}'
init:
  - 'git config --global core.autocrlf true'
branches:
  only:
    - master
    - develop
skip_commits:
  files:
    - LICENSE
    - README.md
environment:
  # nodejs_version: 18
  ruby_version: 32
install:
  # - ps: 'Install-Product node $env:nodejs_version'
  - 'mkdir C:\Users\appveyor\AppData\Roaming\npm'
  - 'node --version && npm --version'
  - 'npx antora -v'
  - 'npm i @antora/lunr-extension'
  - 'set PATH=C:\Ruby%ruby_version%\bin;%PATH%'
  - 'ruby -v && gem -v'
  - 'gem install asciidoctor-epub3'
  - 'asciidoctor-epub3 -v'
  - 'gem install asciidoctor-pdf'
  - 'asciidoctor-pdf -v'
before_build:
  - 'if exist build rd /Q /S build'
build_script:
  - 'npx antora antora-playbook.yml'
  - 'asciidoctor-epub3 -D output docs/modules/ROOT/book.adoc -t'
  - 'asciidoctor-epub3 -o output/book-ctf.epub -a is_ctf=1 docs/modules/ROOT/book.adoc -t'
  - 'asciidoctor-pdf -D output -a compress -a pdf-theme=basic -a pdf-themesdir=resources/themes -a pdf-fontsdir=resources/fonts docs/modules/ROOT/book.adoc -t'
  - 'asciidoctor-pdf -o output/book-ctf.pdf -a is_ctf=1 -a compress -a pdf-theme=basic -a pdf-themesdir=resources/themes -a pdf-fontsdir=resources/fonts docs/modules/ROOT/book.adoc -t'
test: off
artifacts:
  - path: 'build'
  - path: 'output/book.epub'
  - path: 'output/book-ctf.epub'
  - path: 'output/book.pdf'
  - path: 'output/book-ctf.pdf'
deploy:
  provider: FTP
  protocol: sftp
  host: ssh.strato.de
  username: sftp_pwning-juice-shop@kimminich.de
  password:
    secure: U4XjimwWlcw7K+YEw8GfSNuWoWQJZk0+PAqXclKWz6k=
  folder: antora
  application: build.zip
  on:
    branch:
      - master
      - develop
notifications:
  -
    provider: Slack
    incoming_webhook:
      secure: KzO8e88B0LKqAI0BQM6lNhCIn9rxAava3AcdVJDyTw420OLIAlK+qzzbLXaR0jSH9zIJz9zu0iGS1iaqu9Co+6owYUrHJlBGrUZ/lZNCsDo=
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
