site:
  title: Pwning OWASP Juice Shop
  url: https://juice-shop.herokuapp.com
  start_page: index.adoc
content:
  sources:
  - url: .
    start_path: docs
    branches: [antora-migration, antora-develop]
ui:
  bundle:
    url: /Users/parthnanda/Desktop/Gsoc/JuiceShop-UI-antora/build/ui-bundle.zip
    snapshot: true
output:
  dir: ./build

antora:
  extensions:
  - '@antora/lunr-extension'
