site:
  title: Pwning OWASP Juice Shop
  start_page: introduction::readme.adoc
content:
  sources:
  - url: ./
    start_path:
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./docs

antora:
  extensions:
  - '@antora/lunr-extension'
