site:
  title: Pwning OWASP Juice Shop
  url: /
  start_page: index.adoc
content:
  sources:
  - url: .
    start_path: docs
    branches: [master, develop]
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./build

antora:
  extensions:
  - '@antora/lunr-extension'
